# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: eurion-os
description: "Eurion OS - desktop europeo, sicuro-by-design (alpha) basato su Fedora Atomic + KDE"

# Base consigliata KDE: kinoite-main
base-image: ghcr.io/ublue-os/kinoite-main

modules:
  # Flatpak “baseline consumer/office” (installati automaticamente)
  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          title: Flathub (system)
        install:
          - org.libreoffice.LibreOffice
          - org.keepassxc.KeePassXC
          - org.videolan.VLC
          - org.telegram.desktop
          - com.usebottles.bottles
